create Database Grocessory_db;

use grocessory_db;

-- Analysis Questions


-- 1. Supplier Table

CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

select * from supplier;

-- Analysis Questions

-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.

-- How many suppliers are there in the database?


SELECT COUNT(sup_id) AS total_suppliers
FROM supplier;

select* from products;
select * from supplier;
-- Which supplier provides the most products?


SELECT s.sup_name,
COUNT(p.prod_id) AS total_products
FROM supplier as s
JOIN products as p 
ON s.sup_id = p.sup_id
GROUP BY s.sup_name
ORDER BY total_products DESC
Limit 1;

-- What is the average price of products from each supplier?


SELECT s.sup_name,
AVG(p.price) AS average_price
FROM supplier s
JOIN products p 
ON s.sup_id = p.sup_id
GROUP BY s.sup_name;



-- Which suppliers contribute the most to total product sales (by revenue)?
select * from order_details;

SELECT s.sup_name,
SUM(od.total_price) AS total_revenue
FROM supplier as s
JOIN products as p ON s.sup_id = p.sup_id
JOIN order_details as od ON p.prod_id = od.prod_id
GROUP BY s.sup_name
ORDER BY total_revenue DESC;


-- 2. Categories Table

CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

select * from categories;
select * from products;

-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.

-- How many products exist in each category?

select c.cat_name,count(pr.prod_name) as total_products
from products as pr
join categories as c
on c.cat_id=pr.cat_id
group by c.cat_name;


-- What is the average price of products by category?

select avg(pr.price) as avg_priceof_products ,c.cat_name
from categories as c
join products as pr
on c.cat_id=pr.cat_id
group by c.cat_name;


-- Which products have the highest total sales volume (by quantity)?

select * from order_details;
select* from products;

select pr.prod_name,ord.quantity,sum(ord.total_price) as highest_total_sales
from order_details as ord
join products as pr
on pr.prod_id=ord.prod_id
group by ord.quantity,pr.prod_name
order by highest_total_sales desc
limit 1;



-- What is the total revenue generated by each product?

select pr.prod_name,sum(ord.total_price) as total_revenue
from products as pr
join order_details as ord 
on ord.prod_id=pr.prod_id
group by prod_name;


-- How do product sales vary by category and supplier?


-- 3. Employees Table

CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

select * from employees;
select * from orders;

-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.

-- How many employees have processed orders?

SELECT COUNT(Distinct emp_id) AS employees_processed_orders
FROM orders;

-- Which employees have handled the most orders?

select * from orders;
select * from employees;
select * from order_details;

SELECT e.emp_name,
COUNT(o.ord_id) AS total_orders
FROM employees AS e
JOIN orders AS o ON e.emp_id = o.emp_id
GROUP BY e.emp_name
ORDER BY total_orders DESC;

-- What is the total sales value processed by each employee?

SELECT e.emp_name,
SUM(od.total_price) AS total_sales
FROM employees e
JOIN orders AS o ON e.emp_id = o.emp_id
JOIN order_details AS od ON o.ord_id = od.ord_id
GROUP BY e.emp_name;



-- What is the average order value handled per employee?

SELECT e.emp_name,
AVG(order_total) AS average_order_value
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN (
    SELECT ord_id,
           SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) AS order_summary
ON o.ord_id = order_summary.ord_id
GROUP BY e.emp_name;


-- 4. Customers Table

CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

select * from customers;
select * from orders;

-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.

-- How many unique customers have placed orders?

SELECT COUNT(DISTINCT cust_id) AS total_customers
FROM orders;



-- Which customers have placed the highest number of orders?

SELECT c.cust_id, c.cust_name, COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_orders DESC;

select * from order_details;
select * from orders;
-- What is the total and average purchase value per customer?

SELECT c.cust_id, c.cust_name,
SUM(od.total_price) AS total_purchase
FROM customers as c
JOIN orders as  o ON c.cust_id = o.cust_id
JOIN order_details as od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name;

SELECT c.cust_id, c.cust_name,
AVG(od.total_price) AS average_purchase
FROM customers as c
JOIN orders as o ON c.cust_id = o.cust_id
JOIN order_details  as od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name;


-- Who are the top 5 customers by total purchase amount?

select * from customers ;
select * from orders;
select * from order_details;
select * from products;

SELECT c.cust_id, c.cust_name,
SUM(od.total_price) AS total_purchase
FROM customers as c
JOIN orders as o ON c.cust_id = o.cust_id
JOIN order_details as od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase DESC
LIMIT 5;


  
  -- 5. Products Table

CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from products;

-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.

-- How many products exist in each category?

select * from products;
select * from categories;



SELECT cat.cat_name,
COUNT(p.prod_id) AS total_products
FROM categories as cat
JOIN products as p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_name;



-- What is the average price of products by category?

SELECT cat.cat_name,
AVG(p.price) AS average_price
FROM categories as cat
JOIN products as p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_name;


-- Which products have the highest total sales volume (by quantity)?

select * from order_details;
select * from products;



SELECT p.prod_name,
SUM(od.quantity) AS total_quantity_sold
FROM products as p
JOIN order_details as od ON p.prod_id = od.prod_id
GROUP BY p.prod_name
ORDER BY total_quantity_sold DESC;


-- What is the total revenue generated by each product?

SELECT p.prod_name,
SUM(od.total_price) AS total_revenue
FROM products as p
JOIN order_details as od ON p.prod_id = od.prod_id
GROUP BY p.prod_name;


select * from categories;

-- How do product sales vary by category and supplier?

SELECT cat.cat_name,
s.sup_name,
SUM(od.total_price) AS total_sales
FROM order_details as od
JOIN products as p ON od.prod_id = p.prod_id
JOIN categories  as cat ON p.cat_id = cat.cat_id
JOIN supplier  as s ON p.sup_id = s.sup_id
GROUP BY cat.cat_name, s.sup_name;


-- 6. Orders Table

CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from orders;

-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.

-- How many orders have been placed in total?


SELECT COUNT(ord_id) AS total_orders
FROM orders;

-- What is the average value per order?

select * from order_details;

SELECT AVG(order_total) AS average_order_value
FROM (
    SELECT ord_id,
	SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) AS order_summary;



-- On which dates were the most orders placed?

select * from orders;

SELECT order_date,
COUNT(ord_id) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY total_orders DESC;




-- 7. Order_Details Table

CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from order_details;

-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.


-- What is the relationship between quantity ordered and total price?





select prod_id, quantity, each_price,(quantity*each_price) as total_price
from order_details;


-- What is the average quantity ordered per product?



SELECT 
p.prod_name,
AVG(od.quantity) AS avg_quantity_ordered
FROM order_details as od
JOIN products as p 
ON od.prod_id = p.prod_id
GROUP BY p.prod_name
ORDER BY avg_quantity_ordered DESC;



-- How does the unit price vary across products and orders?


SELECT 
p.prod_name,
od.ord_id,
od.each_price
FROM order_details as od
JOIN products as p
ON od.prod_id = p.prod_id
ORDER BY p.prod_name, od.each_price;






